package entitiesip;

//elenco dei comandi presenti nel protocollo di comunicazione

public enum CommCommands {
	CREATEACCOUNT,DELETEACCOUNT,ACTIVATION,LOGIN,LOGINADMIN,EDITUSER,CHECKEMAIL,CHECKNAMEGAME,CHECKNICK,CHECKPASSWORD,CHECKPASSWORDADMIN,CHECKAVVIO,
	RESETPASSWORD,EDITUID,EDITNAME,EDITSURNAME,EDITNICK,EDITPASSWORD,EDITPASSWORDADMIN,GETADMIN,GETNAME,GETUSER,DELETEGAME,GETSCORES,ADDWORD,GETWORD,
	GETSURNAME,GETNICK,GETISCRITTI,GETRICHIESTI,GETNICKMATCH,GETRANDOMCHAR,NEWGAME,LISTGAME,NEWMATCH,UPDATEISCRITTI,SETABBANDONO,GETSHOST,GETUSERPOSTGRES,
	GETPASSWPOSTGRES,CLOSE

}
